<template>
  <div id="chatbot">
    <ChatArea 
      width="360px"
      height="500px"
      :title="title"
      ref="chat_area"
      :position="position"
      :bubbleHeight="`${bubbleHeight + bubbleMargin + 2}px`"
    />
    <Bubble
      :width="`${bubbleWidth}px`"
      :height="`${bubbleHeight}px`"
      :margin="`${bubbleMargin}px`"
      background_color="lightgray"
      border="1px solid"
      :position="position"
      @bubble_click="bubble_click"
    />
  </div>
</template>

<script>
import Bubble from './BubbleComponent.vue'
import ChatArea from './ChatAreaComponent.vue'

export default {
  components: {
    Bubble,
    ChatArea
  },
  props: {
    position: { type: String, default: 'top-left' },
    title: { type:String, default: 'Título' }
  },
  data() {
    return {
      chat_visible: false,
      bubbleWidth: 60,
      bubbleHeight: 60,
      bubbleMargin: 5,
    }
  },
  methods: {
    bubble_click(){
      this.chat_visible = !this.chat_visible;
      this.$refs.chat_area.setVisible( this.chat_visible );
    }
  },
  mounted(){
    this.$refs.chat_area.setWelcomeMessage({
      html: "Neste espaço você informará uma <strong>mensagem de boas vindas</strong> !"
    })
  }
}
</script>

<style scoped>
.scale-in-ver-bottom {
	-webkit-animation: scale-in-ver-bottom 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
	animation: scale-in-ver-bottom 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2022-1-26 15:20:14
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation scale-in-ver-bottom
 * ----------------------------------------
 */
@-webkit-keyframes scale-in-ver-bottom {
  0% {
    -webkit-transform: scaleY(0);
            transform: scaleY(0);
    -webkit-transform-origin: 0% 100%;
            transform-origin: 0% 100%;
    opacity: 1;
  }
  100% {
    -webkit-transform: scaleY(1);
            transform: scaleY(1);
    -webkit-transform-origin: 0% 100%;
            transform-origin: 0% 100%;
    opacity: 1;
  }
}
@keyframes scale-in-ver-bottom {
  0% {
    -webkit-transform: scaleY(0);
            transform: scaleY(0);
    -webkit-transform-origin: 0% 100%;
            transform-origin: 0% 100%;
    opacity: 1;
  }
  100% {
    -webkit-transform: scaleY(1);
            transform: scaleY(1);
    -webkit-transform-origin: 0% 100%;
            transform-origin: 0% 100%;
    opacity: 1;
  }
}

.scale-out-ver-bottom {
	-webkit-animation: scale-out-ver-bottom 0.5s cubic-bezier(0.550, 0.085, 0.680, 0.530) both;
	animation: scale-out-ver-bottom 0.5s cubic-bezier(0.550, 0.085, 0.680, 0.530) both;
}
/* ----------------------------------------------
 * Generated by Animista on 2022-1-26 18:2:21
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation scale-out-ver-bottom
 * ----------------------------------------
 */
@-webkit-keyframes scale-out-ver-bottom {
  0% {
    -webkit-transform: scaleY(1);
            transform: scaleY(1);
    -webkit-transform-origin: 0% 100%;
            transform-origin: 0% 100%;
    opacity: 1;
  }
  100% {
    -webkit-transform: scaleY(0);
            transform: scaleY(0);
    -webkit-transform-origin: 0% 100%;
            transform-origin: 0% 100%;
    opacity: 1;
  }
}
@keyframes scale-out-ver-bottom {
  0% {
    -webkit-transform: scaleY(1);
            transform: scaleY(1);
    -webkit-transform-origin: 0% 100%;
            transform-origin: 0% 100%;
    opacity: 1;
  }
  100% {
    -webkit-transform: scaleY(0);
            transform: scaleY(0);
    -webkit-transform-origin: 0% 100%;
            transform-origin: 0% 100%;
    opacity: 1;
  }
}
</style>
